// <auto-generated />
namespace Merit.BarCodeScanner.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Column_DateOfShift_On_Table_BlockShift : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Column_DateOfShift_On_Table_BlockShift));
        
        string IMigrationMetadata.Id
        {
            get { return "201709180252295_Add_Column_DateOfShift_On_Table_BlockShift"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
